# Generated by Django 2.2.18 on 2021-04-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_product'),
        ('Farmer', '0003_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Id', models.CharField(default='ABC', max_length=50, unique=True)),
                ('Quantity', models.IntegerField()),
                ('Sub_Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Payment_Mode', models.CharField(default=0, max_length=100)),
                ('Order_Status', models.CharField(max_length=100)),
                ('Order_Date', models.DateTimeField(auto_now=True)),
                ('Status_Date', models.DateTimeField(auto_now=True)),
                ('Address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Farmer.Delivery_Address')),
                ('Farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Farmer.Farmer_Registration')),
                ('Seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.Seller_Registration')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.Product')),
            ],
        ),
    ]
