# Generated by Django 2.2.18 on 2021-04-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=150)),
                ('Last_Name', models.CharField(max_length=150)),
                ('Mobile_Number', models.IntegerField()),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Message', models.TextField(max_length=1000)),
            ],
        ),
    ]
