# Generated by Django 2.2.18 on 2021-04-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=150)),
                ('Last_Name', models.CharField(max_length=150)),
                ('Mobile_Number', models.IntegerField()),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Shop_Name', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=120)),
            ],
        ),
    ]
